import{S as a}from"./assets/vendor-6f78bbeb.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))c(e);new MutationObserver(e=>{for(const i of e)if(i.type==="childList")for(const o of i.addedNodes)o.tagName==="LINK"&&o.rel==="modulepreload"&&c(o)}).observe(document,{childList:!0,subtree:!0});function s(e){const i={};return e.integrity&&(i.integrity=e.integrity),e.referrerPolicy&&(i.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?i.credentials="include":e.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function c(e){if(e.ep)return;e.ep=!0;const i=s(e);fetch(e.href,i)}})();const n=[{preview:"../images/preview-object-1.jpg",original:"../images/original-object-1.jpg",description:"Object-1"},{preview:"../images/preview-object-2.jpg",original:"../images/original-object-2.jpg",description:"Object-2"},{preview:"../images/preview-object-3.jpg",original:"../images/original-object-3.jpg",description:"Object-3"},{preview:"../images/preview-object-4.jpg",original:"../images/original-object-4.jpg",description:"Object-4"},{preview:"../images/preview-object-5.jpg",original:"../images/original-object-5.jpg",description:"Object-5"},{preview:"../images/preview-object-6.jpg",original:"../images/original-object-6.jpg",description:"Object-6"},{preview:"../images/preview-object-7.jpg",original:"../images/original-object-7.jpg",description:"Object-7"},{preview:"../images/preview-object-8.jpg",original:"../images/original-object-8.jpg",description:"Object-8"},{preview:"../images/preview-object-9.jpg",original:"../images/original-object-9.jpg",description:"Object-9"}],l=document.querySelector("ul.gallery"),g=n.map(r=>`<li class="gallery-item">
<a class="gallery-link" href="${r.original}">
<img 
class="gallery-image"
src="${r.preview}"
alt="${r.description}"> 
</a>
</li>`).join("");l.insertAdjacentHTML("beforeend",g);new a(".gallery a",{captionsData:"alt",captionDelay:250});
//# sourceMappingURL=commonHelpers.js.map
